# Generated by Django 2.2 on 2020-12-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудник'},
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
